services:
    bite_codes_component_taxonomy.doctrine_listener.taxonomy_listener:
        class: BiteCodes\TaxonomyBundle\Doctrine\Listener\TaxonomyListener
        public: false
        arguments:
            - '@annotations.reader'
        tags:
            - { name: doctrine.event_subscriber, priority: 100 }

    bite_codes_component_taxonomy.doctrine_listener.taxonomy_event_subscriber:
        class: BiteCodes\TaxonomyBundle\Doctrine\Listener\TaxonomyEventSubscriber
        public: false
        arguments:
            - '@annotations.reader'
        tags:
            - { name: doctrine.event_subscriber }

    bite_codes_component_taxonomy.form.taxonomy_root_type:
        class: BiteCodes\TaxonomyBundle\Form\TaxonomyRootType
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }

    bite_codes_taxonomy.services.taxonomy_manager:
        class: BiteCodes\TaxonomyBundle\Services\TaxonomyManager
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@annotations.reader'

    bite_codes_component_taxonomy.command.taxonomy_update_command:
        class: BiteCodes\TaxonomyBundle\Command\TaxonomyUpdateCommand
        public: false
        arguments:
            - '@bite_codes_taxonomy.services.taxonomy_manager'
        tags:
            - { name: console.command }
